apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-apiTest5
  description: "Eine Beschreibung meiner API"
  tags:
    - java
    - data
  annotations:
    backstage.io/managed-by-location: url:http://github.com/test/testApi-info.yaml
  links:
    - url: https://dashboard.example.com
  jira/project-key: ...
      

spec:
  type: openapi
  lifecycle: production
  owner: team-x
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
